name: "POCSAG Decoder"
slug: "pocsag_decoder"
description: "Decode POCSAG pager messages and send to MQTT"
version: "2.0.0"

startup: services
boot: auto

init: false
host_network: true

devices:
  - /dev/bus/usb

arch:
  - aarch64

options:
  frequency: 439.9875
  gain: 30
  mqtt_topic: pager/messages
  baud: POCSAG1200
  debug: false

schema:
  frequency: float
  gain: int
  mqtt_topic: str
  baud: list(POCSAG512|POCSAG1200|POCSAG2400)
  debug: bool
